### ISSUE TITLE
Pull in VA state info

### ISSUE THREAD

**Issue by pjz** [resistbot/contact-officials#25]
There's a VA House export into CSV [here](https://virginiageneralassembly.gov/house/members/members.php) but the only machine readable format I can find for the VA Senate is an [Excel Spreadsheet](https://apps.senate.virginia.gov/Portal/Resources/VAsen.xlsx) on their [Downloadable Lists](https://apps.senate.virginia.gov/Senator/downloadablelists.php) page.

**Comment by jasonkb** [comment]
This is handled by Discovery.

**Comment by pjz** [comment]
Where's Discovery?

**Comment by jasonkb** [comment]
https://github.com/resistbot/discovery ! It pulls all state legislature data from Open States (https://openstates.org).

**Comment by pjz** [comment]
Discovery must not be public - that link 404s for me - which explains why I didn't find it :)
