### ISSUE TITLE
Create form for NJ Governor

### ISSUE THREAD

**Issue by chris-erickson** [resistbot/contact-officials#33]
https://www.state.nj.us/governor/contact/all/

**Comment by csnardi** [comment]
I also have a mostly complete form for New Jersey, but we need a new variable to represent a phone number with no dashes, as apparently that is a requirement of this form.

**Comment by jasonkb** [comment]
@csnardi easy enough in Mercury eh?

**Comment by jasonkb** [comment]
@csnardi https://github.com/resistbot/mercury/pull/101 will give you $PHONE_DIGITS_ONLY!
