### ISSUE TITLE
Create form for WA Governor

### ISSUE THREAD

**Issue by chris-erickson** [resistbot/contact-officials#35]
https://www.governor.wa.gov/contact/contact/send-gov-inslee-e-message

**Comment by jasonkb** [comment]
Woooo go @brianm

**Comment by jasonkb** [comment]
@brianm I'm sorry you ended up with such a nasty form for your first one! This one ended up needing some craziness in Mercury (resistbot/mercury#103) to deal with the iframe and the alert() that is triggered on successful submission. I promise other states will (probably) (hopefully) (if you're not again really unlucky) be easier : )
