### ISSUE TITLE
Create form for SC Governor

### ISSUE THREAD

**Issue by chris-erickson** [resistbot/contact-officials#37]
https://iqconnect.lmhostediq.com/iqextranet/EForm.aspx?__cid=FSL_SC_GOV&__fid=100000

**Comment by jasonkb** [comment]
🔺 🔺 🔺

**Comment by chris-erickson** [comment]
Javascript maybe?

**Comment by jasonkb** [comment]
@csnardi Hm could you make a branch with your latest try? I'm wondering if we set the success text to something like `Contact the Governor`, if we can just assume success.

**Comment by csnardi** [comment]
It's slightly harder because Selenium raises an exception if I remember correctly. Perhaps we could try some Javascript? Not sure.

**Comment by jasonkb** [comment]
@csnardi Could you make a branch with the config you have? I wonder if we can use JS to... preemptively remove the code that calls `alert()`?

**Comment by jasonkb** [comment]
resistbot/mercury#103 added handling alerts to Mercury!
