### ISSUE TITLE
Create form for DC Governor (Mayor)

### ISSUE THREAD

**Issue by chris-erickson** [resistbot/contact-officials#38]
https://dcforms.dc.gov/webform/executive-office-mayor-ask-mayor

**Comment by jason44406** [comment]
Should the yml file be set up as "governor" or something else?  (mayor?)

**Comment by jasonkb** [comment]
hehe still `governor.yaml`. Resistbot treats the DC mayor like just another governor for better or for worse.

**Comment by jason44406** [comment]
Thought that would be the case, but I wanted to be sure.
