### ISSUE TITLE
Create form for AR House

### ISSUE THREAD

**Issue by lhassell** [resistbot/contact-officials#72]
https://www.arkansashouse.org/about/contact-us

**Comment by lhassell** [comment]
Is there an established protocall for handling emails where no form is present, just an email address? This is the case for the AR Senate as well. I'm willing to put in the time to do the data entry, just want to make sure I'm not causing more problems than I create.

**Comment by jasonkb** [comment]
@lhassell Hi Leif, thank you for making these issues! For state legislatures, we've made form configs in this repo for legislatures that have web contact forms that cover the entire legislature. (At this point, we're basically done, but if you find another state with such forms, definitely make an issue.) For others, like AR, there are no configs to make, and we'll just be emailing or mailing them.
