### ISSUE TITLE
Create form for AR Senate

### ISSUE THREAD

**Issue by lhassell** [resistbot/contact-officials#73]
http://www.arkansas.gov/senate/

**Comment by jasonkb** [comment]
@lhassell Hi Leif, thank you for making these issues! For state legislatures, we've made form configs in this repo for legislatures that have web contact forms that cover the entire legislature. (At this point, we're basically done, but if you find another state with such forms, definitely make an issue.) For others, like AR, there are no configs to make, and we'll just be emailing or mailing them.
